#!/bin/bash

# shellcheck disable=SC2034
PACKAGE_LIST_NEOVIM=(
    bat
    curl
    # Required by mason to provide auto installation of LSPs.
    npm
    python3-pip
    cargo
    # Required by telescope
    ripgrep
    fd-find
    fzf
    lldb
)
