#!/bin/bash

# shellcheck disable=SC2034
PACKAGE_LIST_VSCODE=(
    snapd
    fonts-hack
    black
    clang
    flake8
    shellcheck
    mypy
    # Required by "--no-cov" option in settings.json for VsCode
    python3-pytest-cov
)
