#!/bin/bash

# shellcheck disable=SC2034
PACKAGE_LIST_PACKAGING_TOOLS=(
    sbuild
    debhelper
    debmake
    dh-make
    diffoscope
    dput-ng
    git
    git-buildpackage
    myrepos
    distro-info-data
)
