#!/bin/bash

# shellcheck disable=SC2034
PACKAGE_LIST_MISC_PACKAGES=(
    colordiff
    curl
    podman
    gparted
    make
    msmtp
    neomutt
    nmap
    python3-pip
    rsync
    # caff for KSP
    signing-party
    tree
    virt-manager
    whois
    # For gnome-boxes' shared clipboard (between VM and host)
    # The VM also has to have it installed.
    spice-vdagent
)
