#!/bin/bash

# shellcheck disable=SC2034
PACKAGE_LIST_MICS_PACKAGES=(
    bc
    colordiff
    docker.io
    gparted
    make
    msmtp
    nmap
    python3-pip
    rsync
    screen
    signing-party
    telegram-desktop
    tree
    virt-manager
    whois
)
