#!/bin/bash

# shellcheck disable=SC2034
PACKAGE_LIST_MICS_PACKAGES=(
    bc
    colordiff
    docker.io
    gparted
    make
    msmtp
    nmap
    python3-pip
    rsync
    screen
    signing-party
    telegram-desktop
    tree
    virt-manager
    whois
    # For gnome-boxes' shared clipboard (between VM and host)
    # The VM also has to have it installed.
    spice-vdagent
)
